# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=250, unique=True, verbose_name='client id')),
                ('first_name', models.CharField(max_length=250, verbose_name='first name')),
                ('last_name', models.CharField(max_length=250, verbose_name='last name')),
                ('gender', models.CharField(choices=[('H', 'male'), ('F', 'female')], default='H', max_length=5, verbose_name='gender')),
                ('birth_date', models.DateTimeField(verbose_name='birth date')),
                ('status', models.CharField(choices=[('Actif', 'active'), ('Inactif', 'inactive'), ('Retraite', 'retired')], default='Actif', max_length=25, verbose_name='activity status')),
                ('job', models.CharField(max_length=100, verbose_name='job')),
                ('society', models.CharField(max_length=100, verbose_name='society')),
                ('children', models.IntegerField(default=0, verbose_name='children')),
                ('region', models.CharField(max_length=100, verbose_name='region')),
                ('risk_profile', models.CharField(blank=True, max_length=100, null=True, verbose_name='risk profile')),
                ('enter_date', models.DateTimeField(blank=True, null=True, verbose_name='enter date')),
            ],
        ),
    ]
