# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 21:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=250, unique=True, verbose_name='client id')),
                ('initial_date', models.DateTimeField(verbose_name='initial date')),
                ('initial_amount', models.FloatField(verbose_name='initial amount')),
                ('final_amount', models.FloatField(verbose_name='final amount')),
                ('account_type', models.CharField(choices=[('Assurance vie', 'Life Insurance'), ('Compte titres', 'Securities Account'), ('PEA', 'Equity Savings Plan')], max_length=100, verbose_name='account type')),
                ('profile', models.CharField(max_length=100, verbose_name='profile')),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.CharField(choices=[('H', 'Male'), ('F', 'Female')], default='H', max_length=5, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='client',
            name='risk_profile',
            field=models.CharField(blank=True, choices=[('Dynamique', 'Dynamic'), ('Defensif', 'Defensive'), ('Equilibre', 'Balanced')], max_length=100, null=True, verbose_name='risk profile'),
        ),
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('Actif', 'Active'), ('Inactif', 'Inactive'), ('Retraite', 'Retired')], default='Actif', max_length=25, verbose_name='activity status'),
        ),
        migrations.AddField(
            model_name='account',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bar.Client'),
        ),
    ]
