# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0002_auto_20160226_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_id',
            field=models.CharField(max_length=250, unique=True, verbose_name='account id'),
        ),
    ]
