# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 22:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0003_auto_20160226_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountAnalytics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.IntegerField(verbose_name='period')),
                ('date_start', models.DateTimeField(verbose_name='Date start')),
                ('date_end', models.DateTimeField(verbose_name='Date end')),
                ('account_pl', models.FloatField(verbose_name='Account profit & loss')),
                ('account_perf', models.FloatField(verbose_name='Account Performance')),
                ('account_perf_ann', models.FloatField(verbose_name='Account Performance annualisee')),
                ('account_vol', models.FloatField(verbose_name='Account Volatilite')),
                ('account_max_dd', models.FloatField(verbose_name='Account Maximum Drawdown')),
                ('account_te', models.FloatField(verbose_name='Account Tracking-error')),
                ('bench_pl', models.FloatField(verbose_name='Bench profit & loss')),
                ('bench_perf', models.FloatField(verbose_name='Bench performance')),
                ('bench_perf_ann', models.FloatField(verbose_name='Bench performance annualisee')),
                ('bench_vol', models.FloatField(verbose_name='Bench Volatilite')),
                ('bench_max_dd', models.FloatField(verbose_name='Bench Maximum Drawdown')),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bar.Account')),
            ],
        ),
    ]
