# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 22:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0004_accountanalytics'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccountAnalytics',
            new_name='AccountAnalytic',
        ),
    ]
