# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0005_auto_20160226_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isin', models.CharField(max_length=250, unique=True, verbose_name='ISIN')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('product_type', models.CharField(max_length=250, verbose_name='type')),
                ('pea', models.BooleanField(default=False, verbose_name='equity savings plan')),
                ('asv', models.BooleanField(default=False, verbose_name='life insurance')),
                ('cto', models.BooleanField(default=False, verbose_name='trading account')),
                ('asset', models.CharField(max_length=250, verbose_name='asset')),
                ('zone', models.CharField(max_length=250, verbose_name='zone')),
                ('focus', models.CharField(max_length=250, verbose_name='focus')),
                ('currency', models.CharField(max_length=50, verbose_name='currency')),
                ('management', models.CharField(max_length=100, verbose_name='management')),
                ('description', models.TextField(max_length=1000, verbose_name='description')),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('Assurance vie', 'Life Insurance'), ('Compte titres', 'Trading Account'), ('PEA', 'Equity Savings Plan')], max_length=100, verbose_name='account type'),
        ),
    ]
